sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
addons:
  apt:
    packages:
    - build-essential
    - cmake
    - zlib1g-dev
    - libfreetype6-dev
    - libopenal1
    - libopenal-dev
    - mesa-common-dev
    - libgl1-mesa-dev
    - libboost1.54-dev
    - libsdl1.2-dev
    - libglew-dev
    - qt-sdk
    - libglm-dev
    - libcppunit-dev
script: mkdir build && cd build && cmake --version && cmake .. -DICON_TYPE=none -DSTRICT_USE=1 -DBUILD_ALL=1 && make -j1 && make check
branches:
  only:
    - master
    - travis
notifications:
  irc:
    channels:
      - "irc.freenode.net#arxfatalis"
    on_success: change
    on_failure: always
